USE TiendaVideoJuegos_IUE

SET IDENTITY_INSERT Pais ON
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(004, 'AFGANISTÁN', 'AF', '93');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(248, 'ÅLAND', 'AX', '358');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(008, 'ALBANIA', 'AL', '355');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(276, 'ALEMANIA', 'DE', '49');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(020, 'ANDORRA', 'AD', '376');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(024, 'ANGOLA', 'AO', '244');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(660, 'ANGUILA', 'AI', '1');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(010, 'ANTÁRTIDA', 'AQ', '672');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(028, 'ANTIGUA Y BARBUDA', 'AG', '1');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(682, 'ARABIA SAUDITA', 'SA', '966');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(012, 'ARGELIA', 'DZ', '213');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(032, 'ARGENTINA', 'AR', '54');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(051, 'ARMENIA', 'AM', '374');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(533, 'ARUBA', 'AW', '297');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(036, 'AUSTRALIA', 'AU', '61');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(040, 'AUSTRIA', 'AT', '43');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(031, 'AZERBAIYÁN', 'AZ', '994');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(044, 'BAHAMAS', 'BS', '1');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(050, 'BANGLADÉS', 'BD', '880');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(052, 'BARBADOS', 'BB', '1');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(048, 'BARÉIN', 'BH', '973');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(056, 'BÉLGICA', 'BE', '32');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(084, 'BELICE', 'BZ', '501');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(204, 'BENÍN', 'BJ', '229');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(060, 'BERMUDAS', 'BM', '1');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(112, 'BIELORRUSIA', 'BY', '375');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(068, 'BOLIVIA', 'BO', '591');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(535, 'BONAIRE, SAN EUSTAQUIO Y SABA', 'BQ', '599');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(070, 'BOSNIA Y HERZEGOVINA', 'BA', '387');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(072, 'BOTSUANA', 'BW', '267');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(076, 'BRASIL', 'BR', '55');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(096, 'BRUNÉI', 'BN', '673');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(100, 'BULGARIA', 'BG', '359');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(854, 'BURKINA FASO', 'BF', '226');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(108, 'BURUNDI', 'BI', '257');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(064, 'BUTÁN', 'BT', '975');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(132, 'CABO VERDE', 'CV', '238');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(116, 'CAMBOYA', 'KH', '855');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(120, 'CAMERÚN', 'CM', '237');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(124, 'CANADÁ', 'CA', '1');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(634, 'CATAR', 'QA', '974');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(148, 'CHAD', 'TD', '235');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(152, 'CHILE', 'CL', '56');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(156, 'CHINA', 'CN', '86');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(196, 'CHIPRE', 'CY', '357');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(170, 'COLOMBIA', 'CO', '57');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(174, 'COMORAS', 'KM', '269');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(408, 'COREA DEL NORTE', 'KP', '850');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(410, 'COREA DEL SUR', 'KR', '82');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(384, 'COSTA DE MARFIL', 'CI', '225');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(188, 'COSTA RICA', 'CR', '506');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(191, 'CROACIA', 'HR', '385');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(192, 'CUBA', 'CU', '53');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(531, 'CURAZAO', 'CW', '599');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(208, 'DINAMARCA', 'DK', '45');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(212, 'DOMINICA', 'DM', '1');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(218, 'ECUADOR', 'EC', '593');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(818, 'EGIPTO', 'EG', '20');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(222, 'EL SALVADOR', 'SV', '503');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(784, 'EMIRATOS ÁRABES UNIDOS', 'AE', '971');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(232, 'ERITREA', 'ER', '291');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(703, 'ESLOVAQUIA', 'SK', '421');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(705, 'ESLOVENIA', 'SI', '386');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(724, 'ESPAÑA', 'ES', '34');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(840, 'ESTADOS UNIDOS', 'US', '1');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(233, 'ESTONIA', 'EE', '372');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(231, 'ETIOPÍA', 'ET', '251');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(608, 'FILIPINAS', 'PH', '63');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(246, 'FINLANDIA', 'FI', '358');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(242, 'FIYI', 'FJ', '679');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(250, 'FRANCIA', 'FR', '33');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(266, 'GABÓN', 'GA', '241');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(270, 'GAMBIA', 'GM', '220');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(268, 'GEORGIA', 'GE', '995');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(288, 'GHANA', 'GH', '233');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(292, 'GIBRALTAR', 'GI', '350');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(308, 'GRANADA', 'GD', '1');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(300, 'GRECIA', 'GR', '30');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(304, 'GROENLANDIA', 'GL', '299');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(312, 'GUADALUPE', 'GP', '590');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(316, 'GUAM', 'GU', '1');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(320, 'GUATEMALA', 'GT', '502');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(254, 'GUAYANA FRANCESA', 'GF', '594');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(831, 'GUERNSEY', 'GG', '44');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(324, 'GUINEA', 'GN', '224');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(624, 'GUINEA-BISÁU', 'GW', '245');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(226, 'GUINEA ECUATORIAL', 'GQ', '240');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(328, 'GUYANA', 'GY', '592');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(332, 'HAITÍ', 'HT', '509');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(340, 'HONDURAS', 'HN', '504');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(344, 'HONG KONG', 'HK', '852');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(348, 'HUNGRÍA', 'HU', '36');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(356, 'INDIA', 'IN', '91');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(360, 'INDONESIA', 'ID', '62');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(368, 'IRAK', 'IQ', '964');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(364, 'IRÁN', 'IR', '98');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(372, 'IRLANDA', 'IE', '353');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(074, 'ISLA BOUVET', 'BV', '47');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(833, 'ISLA DE MAN', 'IM', '44');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(162, 'ISLA DE NAVIDAD', 'CX', '61');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(352, 'ISLANDIA', 'IS', '354');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(136, 'ISLAS CAIMÁN', 'KY', '1');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(166, 'ISLAS COCOS', 'CC', '61');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(184, 'ISLAS COOK', 'CK', '682');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(234, 'ISLAS FEROE', 'FO', '298');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(239, 'ISLAS GEORGIAS DEL SUR Y SANDWICH DEL SUR', 'GS', '500');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(334, 'ISLAS HEARD Y MCDONALD', 'HM', '672');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(238, 'ISLAS MALVINAS', 'FK', '500');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(580, 'ISLAS MARIANAS DEL NORTE', 'MP', '1');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(584, 'ISLAS MARSHALL', 'MH', '692');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(612, 'ISLAS PITCAIRN', 'PN', '64');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(090, 'ISLAS SALOMÓN', 'SB', '677');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(796, 'ISLAS TURCAS Y CAICOS', 'TC', '1');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(581, 'ISLAS ULTRAMARINAS DE ESTADOS UNIDOS', 'UM', '1');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(092, 'ISLAS VÍRGENES BRITÁNICAS', 'VG', '1');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(850, 'ISLAS VÍRGENES DE LOS ESTADOS UNIDOS', 'VI', '1');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(376, 'ISRAEL', 'IL', '972');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(380, 'ITALIA', 'IT', '39');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(388, 'JAMAICA', 'JM', '1');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(392, 'JAPÓN', 'JP', '81');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(832, 'JERSEY', 'JE', '44');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(400, 'JORDANIA', 'JO', '962');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(398, 'KAZAJISTÁN', 'KZ', '7');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(404, 'KENIA', 'KE', '254');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(417, 'KIRGUISTÁN', 'KG', '996');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(296, 'KIRIBATI', 'KI', '686');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(414, 'KUWAIT', 'KW', '965');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(418, 'LAOS', 'LA', '856');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(426, 'LESOTO', 'LS', '266');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(428, 'LETONIA', 'LV', '371');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(422, 'LÍBANO', 'LB', '961');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(430, 'LIBERIA', 'LR', '231');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(434, 'LIBIA', 'LY', '218');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(438, 'LIECHTENSTEIN', 'LI', '423');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(440, 'LITUANIA', 'LT', '370');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(442, 'LUXEMBURGO', 'LU', '352');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(446, 'MACAO', 'MO', '853');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(807, 'MACEDONIA', 'MK', '389');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(450, 'MADAGASCAR', 'MG', '261');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(458, 'MALASIA', 'MY', '60');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(454, 'MALAUI', 'MW', '265');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(462, 'MALDIVAS', 'MV', '960');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(466, 'MALÍ', 'ML', '223');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(470, 'MALTA', 'MT', '356');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(504, 'MARRUECOS', 'MA', '212');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(474, 'MARTINICA', 'MQ', '596');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(480, 'MAURICIO', 'MU', '230');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(478, 'MAURITANIA', 'MR', '222');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(175, 'MAYOTTE', 'YT', '262');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(484, 'MÉXICO', 'MX', '52');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(583, 'MICRONESIA', 'FM', '691');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(498, 'MOLDAVIA', 'MD', '373');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(492, 'MÓNACO', 'MC', '377');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(496, 'MONGOLIA', 'MN', '976');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(499, 'MONTENEGRO', 'ME', '382');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(500, 'MONTSERRAT', 'MS', '1');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(508, 'MOZAMBIQUE', 'MZ', '258');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(104, 'MYANMAR', 'MM', '95');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(516, 'NAMIBIA', 'NA', '264');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(520, 'NAURU', 'NR', '674');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(524, 'NEPAL', 'NP', '977');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(558, 'NICARAGUA', 'NI', '505');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(562, 'NÍGER', 'NE', '227');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(566, 'NIGERIA', 'NG', '234');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(570, 'NIUE', 'NU', '683');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(574, 'NORFOLK', 'NF', '672');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(578, 'NORUEGA', 'NO', '47');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(540, 'NUEVA CALEDONIA', 'NC', '687');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(554, 'NUEVA ZELANDA', 'NZ', '64');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(512, 'OMÁN', 'OM', '968');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(528, 'PAÍSES BAJOS', 'NL', '31');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(586, 'PAKISTÁN', 'PK', '92');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(585, 'PALAOS', 'PW', '680');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(275, 'PALESTINA', 'PS', '970');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(591, 'PANAMÁ', 'PA', '507');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(598, 'PAPÚA NUEVA GUINEA', 'PG', '675');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(600, 'PARAGUAY', 'PY', '595');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(604, 'PERÚ', 'PE', '51');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(258, 'POLINESIA FRANCESA', 'PF', '689');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(616, 'POLONIA', 'PL', '48');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(620, 'PORTUGAL', 'PT', '351');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(630, 'PUERTO RICO', 'PR', '1');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(826, 'REINO UNIDO', 'GB', '44');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(732, 'REPÚBLICA ÁRABE SAHARAUI DEMOCRÁTICA', 'EH', '212');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(140, 'REPÚBLICA CENTROAFRICANA', 'CF', '236');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(203, 'REPÚBLICA CHECA', 'CZ', '420');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(178, 'REPÚBLICA DEL CONGO', 'CG', '242');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(180, 'REPÚBLICA DEMOCRÁTICA DEL CONGO', 'CD', '243');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(214, 'REPÚBLICA DOMINICANA', 'DO', '1');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(638, 'REUNIÓN', 'RE', '262');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(646, 'RUANDA', 'RW', '250');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(642, 'RUMANIA', 'RO', '40');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(643, 'RUSIA', 'RU', '7');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(882, 'SAMOA', 'WS', '685');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(016, 'SAMOA AMERICANA', 'AS', '1');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(652, 'SAN BARTOLOMÉ', 'BL', '590');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(659, 'SAN CRISTÓBAL Y NIEVES', 'KN', '1');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(674, 'SAN MARINO', 'SM', '378');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(663, 'SAN MARTÍN', 'MF', '590');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(666, 'SAN PEDRO Y MIQUELÓN', 'PM', '508');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(670, 'SAN VICENTE Y LAS GRANADINAS', 'VC', '1');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(654, 'SANTA ELENA, ASCENSIÓN Y TRISTÁN DE ACUÑA', 'SH', '290');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(662, 'SANTA LUCÍA', 'LC', '1');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(678, 'SANTO TOMÉ Y PRÍNCIPE', 'ST', '239');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(686, 'SENEGAL', 'SN', '221');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(688, 'SERBIA', 'RS', '381');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(690, 'SEYCHELLES', 'SC', '248');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(694, 'SIERRA LEONA', 'SL', '232');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(702, 'SINGAPUR', 'SG', '65');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(534, 'SINT MAARTEN', 'SX', '1');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(760, 'SIRIA', 'SY', '963');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(706, 'SOMALIA', 'SO', '252');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(144, 'SRI LANKA', 'LK', '94');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(748, 'SUAZILANDIA', 'SZ', '268');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(710, 'SUDÁFRICA', 'ZA', '27');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(729, 'SUDÁN', 'SD', '249');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(728, 'SUDÁN DEL SUR', 'SS', '211');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(752, 'SUECIA', 'SE', '46');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(756, 'SUIZA', 'CH', '41');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(740, 'SURINAM', 'SR', '597');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(744, 'SVALBARD Y JAN MAYEN', 'SJ', '47');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(764, 'TAILANDIA', 'TH', '66');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(158, 'TAIWÁN (REPÚBLICA DE CHINA)', 'TW', '886');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(834, 'TANZANIA', 'TZ', '255');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(762, 'TAYIKISTÁN', 'TJ', '992');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(086, 'TERRITORIO BRITÁNICO DEL OCÉANO ÍNDICO', 'IO', '246');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(260, 'TIERRAS AUSTRALES Y ANTÁRTICAS FRANCESAS', 'TF', '262');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(626, 'TIMOR ORIENTAL', 'TL', '670');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(768, 'TOGO', 'TG', '228');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(772, 'TOKELAU', 'TK', '690');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(776, 'TONGA', 'TO', '676');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(780, 'TRINIDAD Y TOBAGO', 'TT', '1');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(788, 'TÚNEZ', 'TN', '216');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(795, 'TURKMENISTÁN', 'TM', '993');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(792, 'TURQUÍA', 'TR', '90');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(798, 'TUVALU', 'TV', '688');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(804, 'UCRANIA', 'UA', '380');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(800, 'UGANDA', 'UG', '256');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(858, 'URUGUAY', 'UY', '598');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(860, 'UZBEKISTÁN', 'UZ', '998');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(548, 'VANUATU', 'VU', '678');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(336, 'VATICANO, CIUDAD DEL', 'VA', '39');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(862, 'VENEZUELA', 'VE', '58');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(704, 'VIETNAM', 'VN', '84');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(876, 'WALLIS Y FUTUNA', 'WF', '681');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(887, 'YEMEN', 'YE', '967');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(262, 'YIBUTI', 'DJ', '253');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(894, 'ZAMBIA', 'ZM', '260');
INSERT INTO Pais(Id, Nombre, CodigoAlfa, Indicativo) VALUES(716, 'ZIMBABUE', 'ZW', '263');
SET IDENTITY_INSERT Pais OFF

SET IDENTITY_INSERT Region ON
INSERT INTO Region(Id, Nombre, Codigo, IdPais) VALUES(91 , 'Amazonas ', 'AMA', 170);
INSERT INTO Region(Id, Nombre, Codigo, IdPais) VALUES(05 , 'Antioquia ', 'ANT', 170);
INSERT INTO Region(Id, Nombre, Codigo, IdPais) VALUES(81 , 'Arauca ', 'ARA', 170);
INSERT INTO Region(Id, Nombre, Codigo, IdPais) VALUES(08 , 'Atlántico ', 'ATL', 170);
INSERT INTO Region(Id, Nombre, Codigo, IdPais) VALUES(11 , 'Bogotá ', 'DC ', 170);
INSERT INTO Region(Id, Nombre, Codigo, IdPais) VALUES(13 , 'Bolívar ', 'BOL', 170);
INSERT INTO Region(Id, Nombre, Codigo, IdPais) VALUES(15 , 'Boyacá ', 'BOY', 170);
INSERT INTO Region(Id, Nombre, Codigo, IdPais) VALUES(17 , 'Caldas ', 'CAL', 170);
INSERT INTO Region(Id, Nombre, Codigo, IdPais) VALUES(18 , 'Caquetá ', 'CAQ', 170);
INSERT INTO Region(Id, Nombre, Codigo, IdPais) VALUES(85 , 'Casanare ', 'CAS', 170);
INSERT INTO Region(Id, Nombre, Codigo, IdPais) VALUES(19 , 'Cauca ', 'CAU', 170);
INSERT INTO Region(Id, Nombre, Codigo, IdPais) VALUES(20 , 'Cesar ', 'CES', 170);
INSERT INTO Region(Id, Nombre, Codigo, IdPais) VALUES(27 , 'Chocó ', 'CHO', 170);
INSERT INTO Region(Id, Nombre, Codigo, IdPais) VALUES(23 , 'Córdoba ', 'COR', 170);
INSERT INTO Region(Id, Nombre, Codigo, IdPais) VALUES(25 , 'Cundinamarca', 'CUN', 170);
INSERT INTO Region(Id, Nombre, Codigo, IdPais) VALUES(94 , 'Guainía ', 'GUA', 170);
INSERT INTO Region(Id, Nombre, Codigo, IdPais) VALUES(95, 'Guaviare ', 'GUV', 170);
INSERT INTO Region(Id, Nombre, Codigo, IdPais) VALUES(41, 'Huila ', 'HUI', 170);
INSERT INTO Region(Id, Nombre, Codigo, IdPais) VALUES(44, 'La Guajira ', 'LAG', 170);
INSERT INTO Region(Id, Nombre, Codigo, IdPais) VALUES(47, 'Magdalena ', 'MAG', 170);
INSERT INTO Region(Id, Nombre, Codigo, IdPais) VALUES(50, 'Meta ', 'MET', 170);
INSERT INTO Region(Id, Nombre, Codigo, IdPais) VALUES(52, 'Nariño ', 'NAR', 170);
INSERT INTO Region(Id, Nombre, Codigo, IdPais) VALUES(54, 'Norte de Santander ', 'NSA', 170);
INSERT INTO Region(Id, Nombre, Codigo, IdPais) VALUES(86, 'Putumayo ', 'PUT', 170);
INSERT INTO Region(Id, Nombre, Codigo, IdPais) VALUES(63, 'Quindío ', 'QUI', 170);
INSERT INTO Region(Id, Nombre, Codigo, IdPais) VALUES(66, 'Risaralda ', 'RIS', 170);
INSERT INTO Region(Id, Nombre, Codigo, IdPais) VALUES(88, 'San Andrés y Providencia ', 'SAP', 170);
INSERT INTO Region(Id, Nombre, Codigo, IdPais) VALUES(68, 'Santander ', 'SAN', 170);
INSERT INTO Region(Id, Nombre, Codigo, IdPais) VALUES(70, 'Sucre ', 'SUC', 170);
INSERT INTO Region(Id, Nombre, Codigo, IdPais) VALUES(73, 'Tolima ', 'TOL', 170);
INSERT INTO Region(Id, Nombre, Codigo, IdPais) VALUES(76, 'Valle del Cauca ', 'VAC', 170);
INSERT INTO Region(Id, Nombre, Codigo, IdPais) VALUES(97, 'Vaupés ', 'VAU', 170);
INSERT INTO Region(Id, Nombre, Codigo, IdPais) VALUES(99, 'Vichada ', 'VID', 170);
SET IDENTITY_INSERT Region OFF